short_term_model_training.feature_engineering_short_term_model:
  column_names:
    - total_consumption
    - Global_intensity
    - Sub_metering_3
    - Sub_metering_1
    - temp
    - day_length
    - tempmax
    - feelslike
    - feelslikemax
    - feelslikemin
    - tempmin
  lags:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 30
    - 90
    - 365
  window_sizes:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 30
    - 90
    - 365

short_term_model_training.feature_splitting_short_term_model:
  target:  total_consumption 
  threshold:  2010-05-17 

short_term_model_training.xgboost_model_params:
  base_score: 0.5
  booster: 'gbtree'
  n_estimators: 1000
  early_stopping_rounds: 50
  objective: 'reg:linear'
  max_depth: 3
  learning_rate: 0.01
  verbose_eval: 100
  data_types:
    boolean_columns: ['is_holiday','conditions_clear', 'conditions_overcast', 'conditions_partiallycloudy', 
      'conditions_rain', 'conditions_rainovercast', 'conditions_rainpartiallycloudy', 
      'conditions_snowovercast', 'conditions_snowpartiallycloudy', 
      'conditions_snowrain', 'conditions_snowrainovercast', 'conditions_snowrainpartiallycloudy'
    ]

